\set ON_ERROR_STOP on

-- Solo para una base PostgreSQL desechable y vacia.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
set search_path = "$user", public, extensions;

do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'anon') then
        create role anon nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'authenticated') then
        create role authenticated nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'service_role') then
        create role service_role nologin bypassrls;
    end if;
end;
$$;

create schema if not exists auth;
create or replace function auth.uid()
returns uuid language sql stable
as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;

create schema if not exists storage;
create table storage.buckets (
    id text primary key,
    name text not null,
    public boolean not null default false,
    file_size_limit bigint,
    allowed_mime_types text[]
);
insert into storage.buckets (id, name, public)
values ('facturas-pdf', 'facturas-pdf', false)
on conflict (id) do nothing;

-- Esquema fisico/economico anterior a la migracion 06.
create table public.facturas (
    id uuid primary key default gen_random_uuid(),
    farmacia text not null default 'PIO' check (farmacia in ('PIO', 'RITA')),
    archivo_nombre text not null,
    archivo_ruta text not null,
    archivo_hash text,
    estado_lectura text not null default 'PENDIENTE'
        constraint facturas_estado_lectura_check
        check (estado_lectura in ('PENDIENTE','PROCESANDO','EXTRAIDA','REVISION','ERROR')),
    requiere_revision boolean not null default false,
    datos_extraidos jsonb not null default '{}'::jsonb,
    fecha_importacion timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now(),
    id_proveedor_albaranes bigint,
    proveedor_nombre text,
    proveedor_cif text,
    numero_factura text,
    fecha_factura date,
    importe_total numeric(14,2),
    base_imponible_total numeric(14,2),
    iva_total numeric(14,2),
    recargo_equivalencia_total numeric(14,2),
    estado_conciliacion text not null default 'PENDIENTE',
    estado_pago text not null default 'SIN_PAGAR',
    diferencia_albaranes numeric(14,2),
    diferencia_aceptada_automaticamente boolean not null default false,
    validada_manualmente boolean not null default false,
    validada_por text,
    fecha_validacion timestamptz,
    constraint facturas_archivo_hash_unico unique (farmacia, archivo_hash)
);

create table public.albaranes (
    id bigint generated by default as identity primary key,
    farmacia text not null,
    id_contador bigint not null,
    id_proveedor text not null,
    proveedor text not null,
    numero_albaran text not null,
    fecha date not null,
    importe_pvp numeric(12,2),
    importe_puc numeric(12,2),
    descuento numeric(8,2),
    estado text default 'Pendiente',
    observaciones text,
    fecha_importacion timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now(),
    constraint albaranes_contador_unico unique (farmacia, id_contador),
    constraint albaranes_numero_unico unique (farmacia, id_proveedor, numero_albaran)
);

\ir ../migrations/06_reestructurar_documentos_y_facturas.sql

-- RLS/grants legacy observados en preflight 2F; ninguna policy legacy.
alter table public.albaranes enable row level security;
alter table public.documentos_facturas enable row level security;
alter table public.facturas enable row level security;
alter table public.facturas_vencimientos enable row level security;
alter table public.facturas_impuestos enable row level security;
alter table public.facturas_albaranes_extraidos enable row level security;
alter table public.facturas_ajustes enable row level security;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on table storage.buckets to anon, authenticated, service_role;
