begin;

create table if not exists public.facturas_movimientos (
    id uuid primary key default gen_random_uuid(),
    factura_id uuid not null references public.facturas(id) on delete cascade,
    normalizacion_ejecucion_id uuid references public.normalizacion_ejecuciones(id) on delete set null,
    orden integer not null check (orden > 0),
    categoria text not null
        check (categoria in (
            'SERVICIO',
            'DESCUENTO',
            'DEVOLUCION',
            'CONDICION_COMERCIAL',
            'GASTO',
            'APORTACION',
            'AJUSTE',
            'OTRO'
        )),
    descripcion_literal text not null,
    sentido text check (sentido is null or sentido in ('CARGO', 'ABONO')),
    base numeric(14,4),
    iva numeric(14,4),
    recargo_equivalencia numeric(14,4),
    importe numeric(14,4),
    independiente boolean not null default true,
    conciliable_farmatic boolean not null default false,
    provenance jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint facturas_movimientos_orden_unico unique (factura_id, orden)
);

drop trigger if exists facturas_movimientos_set_updated_at
    on public.facturas_movimientos;
create trigger facturas_movimientos_set_updated_at
before update on public.facturas_movimientos
for each row execute function public.cf_set_updated_at();

create index if not exists facturas_movimientos_factura_idx
    on public.facturas_movimientos (factura_id);

create table if not exists public.facturas_incidencias (
    id uuid primary key default gen_random_uuid(),
    documento_id uuid references public.documentos_facturas(id) on delete cascade,
    factura_id uuid references public.facturas(id) on delete cascade,
    normalizacion_ejecucion_id uuid references public.normalizacion_ejecuciones(id) on delete set null,
    codigo text not null,
    categoria text not null,
    severidad text not null
        check (severidad in ('INFO', 'AVISO', 'ERROR')),
    bloqueante boolean not null default false,
    mensaje_usuario text not null,
    detalle_tecnico jsonb not null default '{}'::jsonb,
    estado text not null default 'ABIERTA'
        check (estado in ('ABIERTA', 'RESUELTA', 'IGNORADA')),
    provenance jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    resuelta_at timestamptz,
    resuelta_por text,
    constraint facturas_incidencias_ambito_check
        check (num_nonnulls(documento_id, factura_id) = 1)
);

drop trigger if exists facturas_incidencias_set_updated_at
    on public.facturas_incidencias;
create trigger facturas_incidencias_set_updated_at
before update on public.facturas_incidencias
for each row execute function public.cf_set_updated_at();

create index if not exists facturas_incidencias_documento_idx
    on public.facturas_incidencias (documento_id, estado)
    where documento_id is not null;

create index if not exists facturas_incidencias_factura_idx
    on public.facturas_incidencias (factura_id, estado)
    where factura_id is not null;

create table if not exists public.historial_facturas (
    id bigint generated by default as identity primary key,
    documento_id uuid references public.documentos_facturas(id) on delete cascade,
    factura_id uuid references public.facturas(id) on delete cascade,
    evento text not null,
    origen text not null,
    actor text,
    estado_anterior jsonb,
    estado_nuevo jsonb not null,
    detalle jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint historial_facturas_ambito_check
        check (num_nonnulls(documento_id, factura_id) >= 1)
);

create index if not exists historial_facturas_documento_idx
    on public.historial_facturas (documento_id, created_at desc);

create index if not exists historial_facturas_factura_idx
    on public.historial_facturas (factura_id, created_at desc);

create or replace function public.cf_historial_append_only()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    raise exception 'historial_facturas es append-only';
end;
$$;

drop trigger if exists historial_facturas_bloquear_cambios
    on public.historial_facturas;
create trigger historial_facturas_bloquear_cambios
before update or delete on public.historial_facturas
for each row execute function public.cf_historial_append_only();

comment on table public.historial_facturas is
    'Registro append-only de transiciones tecnicas y funcionales.';

commit;
